language: cpp

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise
        packages:
            - g++-6
            - clang-5.0
matrix:
    include:
        - os: linux
          env: CXX_COMPILER=clang++-5.0
        - os: linux
          env: CXX_COMPILER=g++-6
        - os: osx
          osx_image: xcode8.3
          env: CXX_COMPILER=clang++

script:
  - make -C tests check CXX=${CXX_COMPILER}

